[package]
name = "aizumi"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "client"

[dependencies]
actix-web = "4"
futures = "0.3.30"
reqwest = "0.12"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.118"
tokio = { version = "1.38.0", features = ["full"] }
